### ISSUE TITLE
Add Floodlight and Stickupcam support to HomeAssistant

### ISSUE THREAD

**Issue by subnetangel** [tchellomello/python-ring-doorbell#59]
@tchellomello Ok I can validate that the Library can see the Flood light cam as per my tests below:

```
Account ID:  [REDACTED]
Address:    [REDACTED]
Family:     stickup_cams
ID:          [REDACTED]
Name:       Front house
Timezone:   America/Chicago
Wifi Name:   [REDACTED]
Wifi RSSI:  -52
Connection Status:  online
Volume:     5
Volume:     5
https://ring-transcoded-videos.s3.amazonaws.com/6477917516918700692.mp4?X-Amz-Expires=3600&X-Amz-Date=20171017T173520Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential= [REDACTED]/20171017/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature= [REDACTED]
Alert Status:  None
```
 This means it sees my Flood Light cam as a Stickup cam, and I saw that in issue: https://github.com/tchellomello/python-ring-doorbell/issues/38 

They were able to get the data for the Flood lights and Siren working. 

What else can I do to help test on HA?

PS> This is the python code I used to test:

```
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')

myring.is_connected
True



for dev in list(myring.stickup_cams + myring.chimes + myring.doorbells):

    # refresh data
    dev.update()

    print('Account ID: %s' % dev.account_id)
    print('Address:    %s' % dev.address)
    print('Family:     %s' % dev.family)
    print('ID:         %s' % dev.id)
    print('Name:       %s' % dev.name)
    print('Timezone:   %s' % dev.timezone)
    print('Wifi Name:  %s' % dev.wifi_name)
    print('Wifi RSSI:  %s' % dev.wifi_signal_strength)
    print('Connection Status:  %s' % dev.connection_status)    

    # setting dev volume
    print('Volume:     %s' % dev.volume)
    dev.volume = 5
    print('Volume:     %s' % dev.volume)
    print(dev.recording_url(dev.last_recording_id))
    print('Alert Status:  %s' % dev.check_alerts())
```

**Comment by tchellomello** [comment]
@subnetangel  is this issue addressed by the PR #58 ?

**Comment by tchellomello** [comment]
stickup camera support has been added to Hass. please give a try on the dev branch to see if works for.you

**Comment by tchellomello** [comment]
I'm closing this for now. feel free to report if you hit any problems. Thank you

**Comment by aLTeReGo-SWI** [comment]
I've added my Ring Floodlight to HA, and the camera and sensors appear as expected. There are however, no switches or lights that appear in HA to control the flood lights or siren. Is there something I'm missing?

**Comment by 1ntr3p1d** [comment]
Any chance this can be re-opened, siren and light still not available.

**Comment by tekmaven** [comment]
Bump on this.  Can this be reopened? I also have the same issue that @aLTeReGo-SWI  @1ntr3p1d have - the siren and light are not available, but I do see the camera and motion sensors.

**Comment by nikotime** [comment]
I am facing the same issue as well.

**Comment by madsmooth** [comment]
I can see 2 of 4 lights and no sirens
